---
apiVersion: v1
kind: Namespace
metadata:
  name: '${ parameters.namespace ?: staging }'
spec:
  finalizers:
  - kubernetes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostname
  name: '${ parameters.namespace ?: staging }'
spec:
  replicas: '${ #toInt( parameters.replicas ?: 3) }'
  selector:
    matchLabels:
      app: hostname
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hostname
        version: v1
    spec:
      containers:
      - image: rstarmer/hostname:v1
        imagePullPolicy: Always
        name: hostname
        resources: {}
      restartPolicy: Always
