apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname
  name: hostname
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hostname
  sessionAffinity: None
  type: LoadBalancer
